#' Import Excel Files to Global Environment
#'
#' @description
#' Reads a single sheet from an Excel file in a specified folder and assigns it
#' to the global environment with the name derived from the file name. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the Excel file.
#' @param file_name A string specifying the name of the Excel file to read, which will
#'   also become the variable name (lowercased, without .xlsx extension).
#' @param sheet A string specifying the name of the sheet to read.
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_excel_files_to_variables(
#'   folder = "data",
#'   file_name = "my_data.xlsx",
#'   sheet = "Sheet1"
#' )
#' # The data is now available as `my_data` in the global environment
#' }
#'
#' @export
import_excel_files_to_variables <- function(folder, file_name, sheet) {
    assign(
        x = stringr::str_to_lower(
            stringr::str_remove(file_name, ".xlsx")
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                openxlsx2::wb_to_df(
                    here::here(folder, file_name),
                    sheet = sheet
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import Microsoft Access Tables to Global Environment
#'
#' @description
#' Reads tables from a Microsoft Access Database and assigns them to the global
#' environment with the name specified by the table_name argument. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param connection A connection object to the Microsoft Access Database
#'   generated by `RODBC::odbcDriverConnect()`.
#' @param table_name A string specifying the name of the table to read, which will
#'   also become the variable name (lowercased).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' # Create connection
#' conn <- RODBC::odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=path/to/db.accdb")
#'
#' # Import table
#' import_access_tables_to_variables(connection = conn, table_name = "MyTable")
#' # The data is now available as `mytable` in the global environment
#' }
#'
#' @export
import_access_tables_to_variables <- function(connection, table_name) {
    assign(
        x = stringr::str_to_lower(table_name),
        value = data.table::as.data.table(
            janitor::clean_names(
                RODBC::sqlFetch(connection, table_name)
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import SAS Files to Global Environment
#'
#' @description
#' Reads a single .sas7bdat SAS file in a specified folder and assigns it to the
#' global environment with the name derived from the file name. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the SAS file.
#' @param file_name A string specifying the name of the .sas7bdat SAS file to read,
#'   which will also become the variable name (lowercased, without .sas7bdat extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_sas_files_to_variables(folder = "data", file_name = "my_data.sas7bdat")
#' # The data is now available as `my_data` in the global environment
#' }
#'
#' @export
import_sas_files_to_variables <- function(folder, file_name) {
    assign(
        x = stringr::str_to_lower(
            stringr::str_remove(file_name, ".sas7bdat")
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                haven::read_sas(
                    here::here(folder, file_name)
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import XPT Files to Global Environment
#'
#' @description
#' Reads a single .xpt file in a specified folder and assigns it to the global
#' environment with the name derived from the file name. The data is converted
#' to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the .xpt file.
#' @param file_name A string specifying the name of the .xpt file to read,
#'   which will also become the variable name (lowercased, without .xpt extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_xpt_files_to_variables(folder = "data", file_name = "my_data.xpt")
#' # The data is now available as `my_data` in the global environment
#' }
#'
#' @export
import_xpt_files_to_variables <- function(folder, file_name) {
    assign(
        x = stringr::str_to_lower(
            stringr::str_remove(file_name, ".xpt")
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                haven::read_xpt(
                    here::here(folder, file_name)
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import CSV Files to Global Environment
#'
#' @description
#' Reads a single .csv file in a specified folder and assigns it to the global
#' environment with the name derived from the file name. The data is read using
#' data.table::fread() and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the .csv file.
#' @param file_name A string specifying the name of the .csv file to read,
#'   which will also become the variable name (lowercased, without .csv extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_csv_files_to_variables(folder = "data", file_name = "my_data.csv")
#' # The data is now available as `my_data` in the global environment
#' }
#'
#' @export
import_csv_files_to_variables <- function(folder, file_name) {
    assign(
        x = stringr::str_to_lower(
            stringr::str_remove(file_name, ".csv")
        ),
        value = janitor::clean_names(
            data.table::fread(
                here::here(folder, file_name)
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Export Data to Excel File
#'
#' @description
#' Exports a data.table or data.frame to an Excel file using writexl.
#' Automatically adds .xlsx extension and exports to "output-files" folder.
#'
#' @param data A data.table or data.frame to be exported.
#' @param file_name A string specifying the file name (without .xlsx extension).
#' @param output_folder A string specifying the output folder. Defaults to "output-files".
#' @param col_names Logical indicating whether to include column names. Defaults to TRUE.
#' @param format_headers Logical indicating whether to format headers. Defaults to TRUE.
#'
#' @return Invisibly returns the path to the saved file.
#'
#' @examples
#' \dontrun{
#' # Export a data.table to Excel
#' export_to_excel(mtcars, "car_data")
#' # Creates "output-files/car_data.xlsx"
#'
#' # Export to a different folder
#' export_to_excel(mtcars, "car_data", output_folder = "results")
#' }
#'
#' @export
export_to_excel <- function(data,
                            file_name,
                            output_folder = "output-files",
                            col_names = TRUE,
                            format_headers = TRUE) {
    file_path <- here::here(output_folder, paste0(file_name, ".xlsx"))

    writexl::write_xlsx(
        data,
        path = file_path,
        col_names = col_names,
        format_headers = format_headers
    )

    invisible(file_path)
}
